### ISSUE TITLE
WP user error on PHP 7.1.0 but not 7.0.13

### ISSUE THREAD

**Issue by Knogobert** [roots/bedrock#289]
I get this error when I try to access the /wp-login.php :

```
Warning: Illegal string offset 'remember' in /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-includes/user.php on line 41

Warning: Cannot assign an empty string to a string offset in /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-includes/user.php on line 41

Warning: Illegal string offset 'user_login' in /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-includes/user.php on line 56

Fatal error: Uncaught Error: Cannot create references to/from string offsets in /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-includes/user.php:56 Stack trace: #0 /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-login.php(784): wp_signon('', '') #1 {main} thrown in /Users/USERNAME/Documents/Websites/PROJECTNAME/web/wp/wp-includes/user.php on line 56
```

As you can see i exchanged my USERNAME and PROJECTNAME.

When I change PHP version from 7.1.0 to 7.0.13 I can access the login page as usual.
So this is just a heads up for you guys! Great work!

---

Bedrock version: 1.7.3

WordPress version: 4.7.1

PHP version: 7.1

OS: macOS 10.11.6 (El Capitan)

**Comment by retlehs** [comment]
are you sure you're on wordpress 4.7.1?

see https://core.trac.wordpress.org/ticket/37071

and looking at the 4.7.1 codebase it looks like it landed: https://github.com/WordPress/WordPress/blob/4.7.1/wp-login.php#L787

**Comment by Knogobert** [comment]
Excuse me, I only believed so because of a new installation. I was on wp 4.7 when this happened. Now I have updated to WP 4.7.1. Should I check if the problem persists for you guys?

**Comment by retlehs** [comment]
actually it was fixed in 4.7.

https://github.com/WordPress/WordPress/blob/4.7/wp-login.php#L787

are you lying about your wordpress versions to us? 😜

**Comment by bormat** [comment]
I fixed it easily by adding 
```
	if ( empty($credentials) ) {
		$credentials = [];
```

on line 39 in wp_signon of user.php in wp-includes.

**Comment by marciobera** [comment]
I returned to 5.6 php version and done!

**Comment by randelsr** [comment]
This problem still persists. composer create-project roots/bedrock installs dependency johnpblock/wordpress v4.3 which is significantly behind the current Wordpress release. 

This is considered a security risk as php 5.6 is deprecated.

To resolve:
a. set php version on host to 5.6 or 7.0
b. install via composer create-project roots/bedrock .
c. go through the typical Wordpress install via instructions
d. *Upgrade Wordpress Core*
e. Change php version on host to latest version (tested on 7.1.24 and verified working)

**Comment by ndls** [comment]
> I fixed it easily by adding
> 
> ```
> 	if ( empty($credentials) ) {
> 		$credentials = [];
> ```
> 
> on line 39 in wp_signon of user.php in wp-includes.

You are a hero, thank you.

**Comment by retlehs** [comment]
35 upvotes on that comment? are y'all using bedrock? don't modify wordpress core... or any other dependencies, since every time you `composer install` those changes are going to be wiped

this was already fixed upstream in wordpress core. not sure what y'all are running into.... but update WP, and update PHP.... but don't modify WP core files. especially if you're using bedrock

hacky option if for some reason you need to actually do this: https://github.com/cweagans/composer-patches

**Comment by randelsr** [comment]
Host PHP version was off, forcing an older version of Bedrock. Update php / composer and you’ll be all set

**Comment by kapilk2io** [comment]
> I fixed it easily by adding
> 
> ```
> 	if ( empty($credentials) ) {
> 		$credentials = [];
> ```
> 
> on line 39 in wp_signon of user.php in wp-includes.

This worked like a charm!!!
